### ISSUE TITLE
Search with zero results throws ArgumentNullException for new Uri

### ISSUE THREAD

**Issue by mwcarroll** [AdrianJSClark/aydsko-iracingdata#105]
If I perform a search that returns zero results , `header.Data.ChunkInfo.BaseDownloadUrl` is null, causing `new Uri` to throw an `ArgumentNullException`. I feel like this should be internally handled by the API wrapper and not passed up the call stack.

https://github.com/AdrianJSClark/aydsko-iracingdata/blob/bf48ba74eaf66d19fc35684edfe599027077ed39/src/Aydsko.iRacingData/DataClient.cs#L997

**Comment by AdrianJSClark** [comment]
Thanks for the report! I'll have a look into this.

**Comment by mwcarroll** [comment]
Perfect, thank you!
