### ISSUE TITLE
Error running example console application

### ISSUE THREAD

**Issue by thomprl** [AdrianJSClark/aydsko-iracingdata#127]
I'm getting the following error when running the example program program.  Looks like it's trying to move the account $ amount to a integer maybe?  Just guessing here.

System.Text.Json.JsonException: 'The JSON value could not be converted to System.Int32. Path: $.account.ir_dollars | LineNumber: 20 | BytePositionInLine: 23.'

**Comment by AdrianJSClark** [comment]
Looks like when I generated that class I had `0` in iRacing credit so it didn't pick up the decimal. Will get a fix out.

I also realise that the sample is probably quite a bit out-of-date, so will update that too.

Thanks for the report, @thomprl!
