### ISSUE TITLE
Cache the results of requests to iRacing.

### ISSUE THREAD

**Issue by robgray** [AdrianJSClark/aydsko-iracingdata#165]
Given iRacing is rate limited and not super quick to call, it might be handy to provide a cache inside of IDataClient that keys on url.  

In my use case I have a few people calling the service so calls like accessing member profiles and overall results, or things that might be called "often" by many people, like current championship standings could do with caching.

**Comment by AdrianJSClark** [comment]
Great idea.

There are some results that should be cached even longer term as well (tracks, lookups, etc).

**Comment by robgray** [comment]
For what it's worth it looks like iRacing caches calls on AWS, using a similar strategy (guid representing a call, I think) as I'm seeing calls to https://scorpio-assets.s3.amazonaws.com/production/data-server/cache/data-services/results/get/<guid>?AWSAccessKeyId=<key> in my debug log.  Sensible defensive programming but it can't hurt to a cache closer to home.

**Comment by AdrianJSClark** [comment]
Yup. Almost every method you call on my client makes 2 HTTP requests. First to call the Data API endpoint, second to convert the link that is returned into JSON that can be processed.

That's what the [`DataResponse<TData>.DataExpires` property](https://adrianjsclark.github.io/aydsko-iracingdata/api/Aydsko.iRacingData.Common.DataResponse-1.html#Aydsko_iRacingData_Common_DataResponse_1_DataExpires) is all about. That would be the basis for expiring the cache items.

**Comment by AdrianJSClark** [comment]
Didn't mean to close it - this is only partially implemented.
