### ISSUE TITLE
Auth concurrency issues

### ISSUE THREAD

**Issue by DuncWatts** [AdrianJSClark/aydsko-iracingdata#185]
I've been using this library within the context of an Azure function application with a queue trigger.  This works by picking up 32 messages at a time to be processed concurrently. 

The login method is not public, but called automatically by each method that retrieves data, therefore when the queue processor starts it hits the iRacing auth endpoint with 32 concurrent auth requests at once.  I have been contacted by iRacing to investigate the high number of auth requests they're receiving.

I have added a workaround with a SemaphoreSlim at the start of the LoginInternalAsync so only the first request will call login and the other requests will wait until the single auth request has completed and won't then call the auth endpoint multiple times.  I'm happy to raise a PR containing this change, but I'm unsure if you want to approach this a different way.

```
        await loginSemaphore.WaitAsync(cancellationToken).ConfigureAwait(false);
        if (IsLoggedIn)
        {
            return;
        }
```

**Comment by AdrianJSClark** [comment]
I think I'd like to avoid doing this within the library itself without serious consideration. Locking is complex and can be app-specific, so I'd prefer to open up a specific method which allows you to move that lock into your own code where you can make the appropriate decisions & analysis on it to avoid deadlocks etc.

I think that with a resolution of #186 implemented this situation can be avoided altogether. I'll leave this issue open until that can be verified though.
