### ISSUE TITLE
Use Cookies from `CookieContainer` when `RestoreCookies` is not set

### ISSUE THREAD

**Issue by SSchulze1989** [AdrianJSClark/aydsko-iracingdata#200]
### Why is there a need to change?

Currently when the client is not logged in yet, the cookies from the container are only checked if also the `RestoreCookies` method is set in the Client options. This ignores the cookies that may already be stored and valid inside the registered `CookieContainer`

### Why is this a problem?

If the client is injected in a scoped service, the service will always receive a new instance where LoggedIn is set to false. This causes the client to make an extra call to the auth page even if valid cookies are already present.

### What should be changed?

The `CookieContainer` can be checked for valid cookies even if `RestoreCookies` method is not set. Then the existing logic can be applied to determine whether the client is already logged in or not. 

This may need an additional check for the lifetime of the cookie to prevent sending an expired cookie in the requests.

**Comment by SSchulze1989** [comment]
@AdrianJSClark if you want i can provide a pr for this feature.

**Comment by AdrianJSClark** [comment]
I've just published a new release which should resolve this issue, @SSchulze1989. Let me know if there are troubles.

**Comment by SSchulze1989** [comment]
@AdrianJSClark working like a charm. The `HttpClient` automatically stores the Cookies in the container and the client stays logged in without the need to do anything else.
