### ISSUE TITLE
Incorrect datatype for RecentEvents.PercentRank field

### ISSUE THREAD

**Issue by JesGot** [AdrianJSClark/aydsko-iracingdata#210]
Aydsko.iRacingData.Member.RecentEvents.PercentRank seems to have an incorrect datatype. 

When calling GetMemberProfileAsync for a certain CustomerId, I got this exception:

System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.recent_events[1].percent_rank | LineNumber: 836 | BytePositionInLine: 31.

Tried changing it to decimal locally and the value was 0.8369153:

![image](https://github.com/AdrianJSClark/aydsko-iracingdata/assets/168639379/3920d99b-ef2a-4b03-bdb4-cef19fe628a7)

**Comment by AdrianJSClark** [comment]
Apologies! I was hoping to get to this over the weekend, but time got away from me. I'll get a fix out ASAP.

Sometimes my sample calls don't include data for all the fields, so I have to guess at the data types. I appreciate the detailed report.
