### ISSUE TITLE
Interval not always returning correct value from race results

### ISSUE THREAD

**Issue by Supersagee** [AdrianJSClark/aydsko-iracingdata#46]
Interval does not seem to always return the correct value when grabbing race results.

Check sessionId: 45238898 where interval value does NOT return correct value.

Check sessionId: 45243121 where interval value IS correct.

**Comment by AdrianJSClark** [comment]
I've looked at both those sessions, @Supersagee, and I don't understand where you think the incorrect values are, sorry.

I do realise that I haven't built out the `Aydsko.iRacingData.Results.Result` type to properly convert from iRacing's representation of a duration to .NET's representation (i.e. converting the "number" type in the JSON to a "TimeSpan" type in the .NET object). I've filed #47 to fix this.

Using an in-progress version of that code, I get the following two data sets for your "incorrect" and "correct" sessions. Both look to have the right values for interval when matched against iRacing's results.

iRacing Results at: https://members.iracing.com/membersite/member/EventResult.do?&subsessionid=45238898

<TABLE><THEAD><TH>DataSet</TH><TH>CustomerId</TH><TH>FinishPosition</TH><TH>FinishPositionInClass</TH><TH>Interval</TH><TH>ClassInterval</TH><TH>LapsComplete</TH></THEAD><TR><TD>Incorrect</TD><TD>438198</TD><TD>0</TD><TD>0</TD><TD>0:00.000</TD><TD>0:00.000</TD><TD>12</TD></TR><TR><TD>Incorrect</TD><TD>128200</TD><TD>1</TD><TD>1</TD><TD>0:05.668</TD><TD>0:05.668</TD><TD>12</TD></TR><TR><TD>Incorrect</TD><TD>564678</TD><TD>2</TD><TD>2</TD><TD>0:06.905</TD><TD>0:06.905</TD><TD>12</TD></TR><TR><TD>Incorrect</TD><TD>50387</TD><TD>3</TD><TD>3</TD><TD>0:08.756</TD><TD>0:08.756</TD><TD>12</TD></TR><TR><TD>Incorrect</TD><TD>43302</TD><TD>4</TD><TD>4</TD><TD>0:12.793</TD><TD>0:12.793</TD><TD>12</TD></TR><TR><TD>Incorrect</TD><TD>733449</TD><TD>5</TD><TD>5</TD><TD>0:22.540</TD><TD>0:22.540</TD><TD>12</TD></TR><TR><TD>Incorrect</TD><TD>552274</TD><TD>6</TD><TD>6</TD><TD>0:48.876</TD><TD>0:48.876</TD><TD>12</TD></TR><TR><TD>Incorrect</TD><TD>218358</TD><TD>7</TD><TD>0</TD><TD>0:56.001</TD><TD>0:00.000</TD><TD>12</TD></TR><TR><TD>Incorrect</TD><TD>542435</TD><TD>8</TD><TD>1</TD><TD>1:09.808</TD><TD>0:13.807</TD><TD>12</TD></TR><TR><TD>Incorrect</TD><TD>734699</TD><TD>9</TD><TD>2</TD><TD>1:09.868</TD><TD>0:13.866</TD><TD>12</TD></TR><TR><TD>Incorrect</TD><TD>703171</TD><TD>10</TD><TD>3</TD><TD>1:09.959</TD><TD>0:13.958</TD><TD>12</TD></TR><TR><TD>Incorrect</TD><TD>396808</TD><TD>11</TD><TD>4</TD><TD>1:14.406</TD><TD>0:18.405</TD><TD>12</TD></TR><TR><TD>Incorrect</TD><TD>586050</TD><TD>12</TD><TD>5</TD><TD>1:15.553</TD><TD>0:19.551</TD><TD>12</TD></TR><TR><TD>Incorrect</TD><TD>676495</TD><TD>13</TD><TD>6</TD><TD>1:15.671</TD><TD>0:19.669</TD><TD>12</TD></TR><TR><TD>Incorrect</TD><TD>551239</TD><TD>14</TD><TD>7</TD><TD>1:17.805</TD><TD>0:21.804</TD><TD>12</TD></TR><TR><TD>Incorrect</TD><TD>638929</TD><TD>15</TD><TD>8</TD><TD>1:18.376</TD><TD>0:22.375</TD><TD>12</TD></TR><TR><TD>Incorrect</TD><TD>176181</TD><TD>16</TD><TD>9</TD><TD>1:19.593</TD><TD>0:23.592</TD><TD>12</TD></TR><TR><TD>Incorrect</TD><TD>628355</TD><TD>17</TD><TD>10</TD><TD>1:53.274</TD><TD>0:57.273</TD><TD>12</TD></TR><TR><TD>Incorrect</TD><TD>374665</TD><TD>18</TD><TD>0</TD><TD>2:02.703</TD><TD>0:00.000</TD><TD>12</TD></TR><TR><TD>Incorrect</TD><TD>639545</TD><TD>19</TD><TD>1</TD><TD>2:03.562</TD><TD>0:00.859</TD><TD>12</TD></TR><TR><TD>Incorrect</TD><TD>209445</TD><TD>20</TD><TD>2</TD><TD>2:07.687</TD><TD>0:04.984</TD><TD>12</TD></TR><TR><TD>Incorrect</TD><TD>635880</TD><TD>21</TD><TD>3</TD><TD>2:11.979</TD><TD>0:09.276</TD><TD>12</TD></TR><TR><TD>Incorrect</TD><TD>621545</TD><TD>22</TD><TD>11</TD><TD>0:00.000</TD><TD>0:00.000</TD><TD>11</TD></TR><TR><TD>Incorrect</TD><TD>724239</TD><TD>23</TD><TD>0</TD><TD>0:00.000</TD><TD>0:00.000</TD><TD>11</TD></TR><TR><TD>Incorrect</TD><TD>551000</TD><TD>24</TD><TD>12</TD><TD>0:00.000</TD><TD>0:00.000</TD><TD>6</TD></TR><TR><TD>Incorrect</TD><TD>471821</TD><TD>25</TD><TD>13</TD><TD>0:00.000</TD><TD>0:00.000</TD><TD>1</TD></TR><TR><TD>Incorrect</TD><TD>736698</TD><TD>26</TD><TD>4</TD><TD>0:00.000</TD><TD>0:00.000</TD><TD>0</TD></TR></TABLE>



iRacing Results at: https://members.iracing.com/membersite/member/EventResult.do?&subsessionid=45243121

<TABLE><THEAD><TH>DataSet</TH><TH>CustomerId</TH><TH>FinishPosition</TH><TH>FinishPositionInClass</TH><TH>Interval</TH><TH>ClassInterval</TH><TH>LapsComplete</TH></THEAD><TR><TD>Correct</TD><TD>147876</TD><TD>0</TD><TD>0</TD><TD>0:00.000</TD><TD>0:00.000</TD><TD>4</TD></TR><TR><TD>Correct</TD><TD>147811</TD><TD>1</TD><TD>1</TD><TD>0:09.354</TD><TD>0:09.354</TD><TD>4</TD></TR><TR><TD>Correct</TD><TD>564678</TD><TD>2</TD><TD>2</TD><TD>0:22.873</TD><TD>0:22.873</TD><TD>4</TD></TR><TR><TD>Correct</TD><TD>333160</TD><TD>3</TD><TD>3</TD><TD>0:28.975</TD><TD>0:28.975</TD><TD>4</TD></TR><TR><TD>Correct</TD><TD>500306</TD><TD>4</TD><TD>4</TD><TD>0:41.526</TD><TD>0:41.526</TD><TD>4</TD></TR><TR><TD>Correct</TD><TD>430062</TD><TD>5</TD><TD>5</TD><TD>1:16.989</TD><TD>1:16.989</TD><TD>4</TD></TR><TR><TD>Correct</TD><TD>595608</TD><TD>6</TD><TD>6</TD><TD>3:43.104</TD><TD>3:43.104</TD><TD>4</TD></TR><TR><TD>Correct</TD><TD>401054</TD><TD>7</TD><TD>0</TD><TD>3:46.411</TD><TD>0:00.000</TD><TD>4</TD></TR><TR><TD>Correct</TD><TD>665129</TD><TD>8</TD><TD>1</TD><TD>4:17.235</TD><TD>0:30.823</TD><TD>4</TD></TR><TR><TD>Correct</TD><TD>413533</TD><TD>9</TD><TD>2</TD><TD>7:08.812</TD><TD>3:22.400</TD><TD>4</TD></TR><TR><TD>Correct</TD><TD>155764</TD><TD>10</TD><TD>7</TD><TD>0:00.000</TD><TD>0:00.000</TD><TD>2</TD></TR><TR><TD>Correct</TD><TD>395936</TD><TD>11</TD><TD>8</TD><TD>0:00.000</TD><TD>0:00.000</TD><TD>2</TD></TR><TR><TD>Correct</TD><TD>592321</TD><TD>12</TD><TD>3</TD><TD>0:00.000</TD><TD>0:00.000</TD><TD>1</TD></TR><TR><TD>Correct</TD><TD>750165</TD><TD>13</TD><TD>4</TD><TD>0:00.000</TD><TD>0:00.000</TD><TD>1</TD></TR><TR><TD>Correct</TD><TD>631540</TD><TD>14</TD><TD>9</TD><TD>0:00.000</TD><TD>0:00.000</TD><TD>1</TD></TR><TR><TD>Correct</TD><TD>488471</TD><TD>15</TD><TD>5</TD><TD>0:00.000</TD><TD>0:00.000</TD><TD>1</TD></TR><TR><TD>Correct</TD><TD>45342</TD><TD>16</TD><TD>10</TD><TD>0:00.000</TD><TD>0:00.000</TD><TD>0</TD></TR><TR><TD>Correct</TD><TD>655380</TD><TD>17</TD><TD>6</TD><TD>0:00.000</TD><TD>0:00.000</TD><TD>0</TD></TR><TR><TD>Correct</TD><TD>631351</TD><TD>18</TD><TD>7</TD><TD>0:00.000</TD><TD>0:00.000</TD><TD>0</TD></TR></TABLE>

**Comment by Supersagee** [comment]
Thank you for looking into it. It must be something I'm doing wrong on my end. Both the raw and converted values for some of the interval results aren't quite right for me. I'll dig in some more and figure out what's going on. Thanks!

**Comment by AdrianJSClark** [comment]
I'll close this issue for now. If your interval pain persists, please feel free to either re-open with additional details or file a new issue.

**Comment by Supersagee** [comment]
I've realized where I went wrong. All my testing was done with session: 45243121. That race was at the Nordschleife, where qualifying is done on  a separate server, meaning that there are no qualifying results for the event.

I was specifically grabbing results from SessionResults[1], which got me the race results at the Nordschleife, but would return Qualifying results, instead of race results, for all other tracks. I'll just set it to grab SessionResults from the last index for race results. A real bonehead mistake that I really should have noticed sooner.

Thanks again for taking a look!

**Comment by AdrianJSClark** [comment]
@Supersagee What you want to look for is the `SessionResult` object where `SimSessionNumber == 0` because that will be the main event which is the race for "Road" type events with the standard official "Warm Up (Practice) / Qualifying / Race" structure.

**Comment by Supersagee** [comment]
@AdrianJSClark Thank you for insight!
