### ISSUE TITLE
Add Custom League Sessions

### ISSUE THREAD

**Issue by AdrianJSClark** [AdrianJSClark/aydsko-iracingdata#70]
Implement support for the `/data/league/cust_league_sessions` endpoint.

**Comment by dennis** [comment]
I'll try to do something useful with this

**Comment by AdrianJSClark** [comment]
Cheers! I'm just not a member of any actual custom leagues so don't have any example data.

**Comment by AdrianJSClark** [comment]
Thanks heaps for adding this, @dennis! Sorry the merge was a bit rocky.
